name: ramp-ua
channels:
  - defaults
dependencies:
  - numpy
  - tqdm
  - pandas
  - python=3.7
  - click
  - pytest
  - matplotlib
  - swifter
  - rpy2
  - tzlocal
  - r-mixdist
  - r-tidyr
  - r-stringr
  - r-readr
  - r-curl
  - bokeh
  - geopandas
  - imageio
  - r-janitor
  - r-stringi
