scenario_name: default # A name describing the scenario. Output data will be stored in a subdirectory with this name.

# Utility parameters for the microsimulation (python) part.
# These can also be passed as command line arguments
microsim:
  scenario: "TestScenario" # name for scenario directory
  iterations: 10 # Number of model iterations. 0 means just run the initialisation.
  data-dir: devon_data # Root directory to load data from
  output: true # Whether to generate output or not
  debug: false # Whether to run some more expensive checks
  repetitions: 1 # How many times to run the model
  lockdown-from-file: true # Read lockdown mobility data from a file?

# Parameters that are used to calibrate the model.
# These can only be passed using the parameters file
microsim_calibration:
  # These multiply the amount of hazard that individuals pass on to shops etc:
  hazard_multiplier_presymptomatic: 1.0
  hazard_multiplier_asymptomatic: 1.0
  hazard_multiplier_symptomatic: 1.0
  # This multiplies the risk received as individuals visit shops etc.
  risk_multiplier: 1.0

disease: # This is where the parameter for the disease model (the R part) can go
  x: 1 # An example, can be removed.
