
name: python-testing

# Only run this for pushes to master, develop-AC and for pull requests to master
on:
  push:
    branches:
    - master
    - develop-AC
  pull_request:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false
        activate-environment: ramp-ua

    # run pytest within conda environment
    - name: Run pytest
      shell: bash -l {0}
      run: |
        conda activate ramp-ua
        pytest